language: python

python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

env:
    - ASYNC_TEST_TIMEOUT=30

services:
    - postgresql
    - mysql

before_script:
    - psql -U postgres < tests/travis/postgre.sql
    - mysql --user=root --password=''  < tests/travis/my.sql

install:
    - make install-deps
    - pip install .

script:
    - flake8
    - py.test tests/
