language: python

dist: xenial

python:
    - "3.5"
    - "3.6"
    - "3.7"

services:
    - docker

env:
    - ASYNC_TEST_TIMEOUT=30

install:
    - docker-compose build
    - docker-compose up --detach

before_script:
    - pip install --upgrade pip
    - pip install poetry
    - poetry install

script:
    - make lint-flake8
    - if [[ $TRAVIS_PYTHON_VERSION != '3.5' ]]; then make lint-black; fi
    - make test

after_script:
    - docker-compose down
