language: python

python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

services:
    - postgresql
    - mysql

before_script:
    - psql -U postgres < tests/travis/postgre.sql
    - mysql --user=root --password=''  < tests/travis/my.sql

install:
    - pip install pipenv
    - pipenv install --dev

script:
    - pipenv run flake8
    - pipenv run py.test tests/
